wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.11
    start_time: 1648579595
    t:
      1:
      - 3
      4: 3.9.11
      5: 0.12.11
      8:
      - 3
      - 5
